# Generated by Django 5.2.1 on 2025-05-25 05:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del autor', max_length=100)),
                ('bio', models.TextField(help_text='Biografía del autor (mínimo 50 caracteres)', validators=[django.core.validators.MinLengthValidator(50)])),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del autor', null=True, upload_to='autores/')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del autor', max_length=254)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso al equipo')),
                ('activo', models.BooleanField(default=True, help_text='¿El autor está activo?')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Tecnología, Deportes)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del artículo', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido completo del artículo (mínimo 100 caracteres)', validators=[django.core.validators.MinLengthValidator(100)])),
                ('resumen', models.TextField(blank=True, help_text='Resumen corto del artículo (máximo 300 caracteres)', max_length=300)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal del artículo', null=True, upload_to='articulos/')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=200, unique=True)),
                ('destacado', models.BooleanField(default=False, help_text='¿Mostrar en artículos destacados?')),
                ('publicado', models.BooleanField(default=True, help_text='¿El artículo está publicado?')),
                ('vistas', models.PositiveIntegerField(default=0, help_text='Número de vistas del artículo')),
                ('autor', models.ForeignKey(help_text='Autor del artículo', on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='news.autor')),
                ('categoria', models.ForeignKey(help_text='Categoría del artículo', on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='news.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(help_text='Nombre del usuario que comenta', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email del usuario (opcional)', max_length=254)),
                ('texto', models.TextField(help_text='Contenido del comentario (mínimo 10 caracteres)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del comentario')),
                ('aprobado', models.BooleanField(default=True, help_text='¿El comentario está aprobado?')),
                ('articulo', models.ForeignKey(help_text='Artículo al que pertenece el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='news.articulo')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['-fecha_publicacion'], name='news_articu_fecha_p_36bdac_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['categoria', '-fecha_publicacion'], name='news_articu_categor_13d903_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['autor', '-fecha_publicacion'], name='news_articu_autor_i_5debd4_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['articulo', 'fecha'], name='news_coment_articul_a18f73_idx'),
        ),
    ]
